---
neovim_build_requirements:
  # For building neovim from source
  - base-devel
  - cmake
  - ninja
  - curl

  # For working with python (pip get's installed in the python package)
  - python
  - python-virtualenv

neovim_additional_packages:
  # lsp support
  - clang
  - pyright
  - lua-language-server
  - bash-language-server

  # for clipboard
  - xclip

  # treesitter requirements
  - tree-sitter-cli
  - nodejs

  # telescope requirements
  - fzf
  - ripgrep
  - fd

  # mason requirements
  - npm

neovim_config_dir: "{{ ~/.config/nvim }}"
neovim_workspace_dir: "{{ ~/workspace/git/hub/neovim_config }}"
neovim_ssl_repo: "git@github.com:jimmy-sama/neovim_config.git"
