#SPDX-License-Identifier: MIT-0
---
# tasks file for roles/dwl

- name: Install Dependencies for building dwl
  community.general.pacman:
    name:
      - wayland
      - wayland-protocols
      - wlroots0.18
      - libxkbcommon
      - pkgconfig
      - mesa
      - libdrm
      - libinput
    state: present
  become: true

- name: Install Dependencies for using my dwl setup
  community.general.pacman:
    name:
      - waybar
      - hyprpaper
      - hyprlock
      - dunst
      - ghostty
      - flameshot
      - wireplumber
      - brightnessctl
      - gimp
    state: present
  become: true

- name: Create the Wallpaper directory
  ansible.builtin.file:
    path: ~/Pictures/Wallpaper
    state: directory

- name: Create the wayland-sessions directory
  ansible.builtin.file:
    path: /usr/share/wayland-sessions
    state: directory
  become: true

- name: Create hypr-tools directory
  ansible.builtin.file:
    path: ~/.config/hypr
    state: directory

- name: Create waybar config directory
  ansible.builtin.file:
    path: ~/.config/waybar
    state: directory

- name: Copy waybar config
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: ~/.config/waybar
  with_fileglob:
    - "files/waybar/*"

- name: Copy hyprpaper config
  ansible.builtin.copy:
    src: wallpaper/hyprpaper.conf
    dest: ~/.config/hypr/hyprpaper.conf

- name: Copy the wallpaper files to the directory
  ansible.builtin.copy:
    src: wallpaper/purple.jpg
    dest: ~/Pictures/Wallpaper/

- name: Copy dwlStartup script to $HOME
  ansible.builtin.copy:
    src: dwl/dwlStartup.sh
    dest: ~/dwlStartup.sh
    mode: 0755

- name: Copy dwl desktop entry
  ansible.builtin.copy:
    src: dwl/dwl.desktop
    dest: /usr/share/wayland-sessions
  become: true
