#SPDX-License-Identifier: MIT-0
---
# tasks file for roles/dwl

- name: Install Dependencies for dwl
  community.general.pacman:
    name:
      - wayland
      - wayland-protocols
      - wlroots0.18
      - libxkbcommon
      - pkgconfig
      - mesa
      - libdrm
      - libinput
      - wmenu
    state: present
  become: true

- name: Install wlroots with paru
  kewlfft.aur.aur:
    name: wlroots-asan-git
    state: absent
  become: true
  become_user: aur_builder
  
