#SPDX-License-Identifier: MIT-0
---
# tasks file for roles/dwl

- name: Install Dependencies for building dwl
  community.general.pacman:
    name:
      - wayland
      - wayland-protocols
      - wlroots0.18
      - libxkbcommon
      - pkgconfig
      - mesa
      - libdrm
      - libinput
    state: present
  become: true

- name: Install Dependencies for using my dwl setup
  community.general.pacman:
    name:
      - waybar
      - ghostty
      - flameshot
      - wireplumber
      - brightnessctl
      - gimp
    state: present
  become: true
