---
os_packages: 
  - bat
  - curl
  - duf
  - fd-find
  - fzf
  - git
  - glow
  - jq
  - lazygit
  - lsd
  - ncdu
  - ranger
  - zoxide
  - zsh

local_bin_path: "~/.local/bin"
github3py_venv_path: "/opt/github3py_venv"
venv_interpreter: "{{ github3py_venv_path }}/bin/python"
fx_gh_owner: "antonmedv"
fx_gh_repo: "fx"
