---
- hosts: localhost
  connection: local

  vars_files:
    secrets.yml

  roles:
    - { role: 'common', tags: 'common' }
    - { role: 'dunst', tags: 'dunst' }
    - { role: 'dwm', tags: 'dwm' }
    - { role: 'firefox', tags: 'firefox' }
    - { role: 'fonts', tags: 'fonts' }
    - { role: 'ghostty', tags: 'ghostty' }
    - { role: 'ly', tags: 'ly' }
    - { role: 'mpd', tags: 'mpd' }
    - { role: 'neovim', tags: 'neovim' }
    - { role: 'picom', tags: 'picom' }
    - { role: 'ranger', tags: 'ranger' }
    - { role: 'rmpc', tags: 'rmpc' }
    - { role: 'rofi', tags: 'rofi' }
    - { role: 'slstatus', tags: 'slstatus' }
    - { role: 'terminal', tags: 'terminal' }
    - { role: 'tmux', tags: 'tmux' }
    - { role: 'vagrant', tags: 'vagrant' }
    - { role: 'zathura', tags: 'zathura' }
    - { role: 'zsh', tags: 'zsh' }
