- name: Quick Playbook
  hosts: localhost
  tasks:
   - name: Print all available facts
     ansible.builtin.debug:
       var: ansible_facts
   - name: Print distribution 
     ansible.builtin.debug:
       msg: "{{ ansible_distribution }}"
