---
- name: Configure my Arch-System
  hosts: localhost
  connection: local
  tasks:
    - name: Include "it worked on my machine" roles
      ansible.builtin.include_role:
        name: "{{ item }}"
      loop:
        - dwm
        - neovim
        - terminal
        - ly
        - common
        - fonts
