---
- name: Configure my Arch-System
  hosts: localhost
  connection: local
  tasks:
    - name: Include "it worked on my machine" roles
      ansible.builtin.include_role:
        name: "{{ item }}"
      loop:
        - neovim
        - terminal
        - common
        - fonts

    - name: Include roles for Desktop Systems
      ansible.builtin.include_role:
        name: "{{ item }}"
      loop:
        - dwm
        - firefox
      when:
        - ansible_facts['form_factor'] == Desktop
        - ansible_facts['form_factor'] == Notebook
