#SPDX-License-Identifier: MIT-0
---
# By the time of creating this role, it is only intended to use with debian!
    
- name: Install required programs for local Ansible development
  become: true
  ansible.builtin.apt:
    name:
      - ansible-core
      - vagrant
      - vagrant-libvirt
      - libvirt-daemon-system
    update_cache: true
    state: present

- name: Ensure User is part of the libvirt group
  become: true
  ansible.builtin.user:
    name: "{{ ansible_facts['user_id'] }}"
    groups: libvirt
    append: true
