---
slstatus_build_requirements:
  - libx11
  - libxft
  - libxinerama

slstatus_https_repo: "https://github.com/jimmy-sama/slstatus_custom.git"
slstatus_ssl_repo: "git@github.com:jimmy-sama/slstatus_custom.git"
slstatus_workspace_dir: "{{ ansible_facts['user_dir'] }}/workspace/git/hub/slstatus_custom"
