---
- name: Install the dwm build requirements and other requirements
  become: true
  community.general.pacman:
    name: "{{ dwm_build_requirements }}"
    state: present

- name: Install other dwm dependencies
  become: true
  community.general.pacman:
    name: "{{ dwm_dependencies }}"
    state: present

- name: Create the Wallpaper directory
  ansible.builtin.file:
    path: "{{ dwm_wallpapers_dir }}"
    state: directory
    mode: '0755'

- name: Extrtact the wallpapaper archive
  ansible.builtin.unarchive:
    src: files/wallpapers.tar.bz2
    dest: "{{ dwm_wallpapers_dir }}"

- name: Clone my custom version of dwm # noqa: latest[git]
  ansible.builtin.git:
    repo: "{{ dwm_ssl_repo }}"
    dest: "{{ dwm_workspace_dir }}"
  notify: Dwm_make

- name: Use the template xinitrc configuration file
  ansible.builtin.copy:
    src: files/.xinitrc
    dest: ~/.xinitrc
    mode: '0755'
