---
- name: Install the dwm build requirements and other requirements
  become: true
  community.general.pacman:
    name: "{{ dwm_build_requirements }}"
    state: present

- name: Install other dwm dependencies
  become: true
  community.general.pacman:
    name: "{{ dwm_dependencies }}"
    state: present

- name: Create the Wallpaper directory
  ansible.builtin.file:
    path: ~/Pictures/Wallpaper
    state: directory
    mode: '0755'

# Instead of copying single files, it would be better to work with archives

- name: Clone my custom version of dwm # noqa: latest[git]
  ansible.builtin.git:
    repo: "{{ dwm_ssl_repo }}"
    dest: "{{ dwm_workspace_dir }}"
  notify: Dwm_make

- name: Use the template xinitrc configuration file
  ansible.builtin.template:
    src: templates/xinitrc.j2
    dest: ~/.xinitrc
    mode: '0755'
