#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config automatic_scheme alternate
bspc config border_width        2
bspc config window_gap          6

bspc config split_ratio            0.5
bspc config single monocle         false
bspc config focus_follows_pointer  true
bspc config borderless_monocle     true
bspc config gapless_monocle        true

bspc rule -a "*:Toolkit:Picture-in-Picture" \
	state=floating sticky=on follow=off focus=on \
	rectangle=640x360+2760+1040

bspc rule -a '*:Toolkit:Picture in Picture' \
	state=floating sticky=on follow=off focus=on \
	rectangle=640x360+2760+1040

dunst &
feh --bg-fill ~/Pictures/localhost.png &
xrandr --output DP-0 --primary --mode 3440x1440 --rate 143.92 &
xsetroot -cursor_name left_ptr

