---
- name: "Inatall Yazi Application"
  ansible.builtin.package:
    name: yazi
    state: latest
  become: true

- name: "Yazi | Config folder"
  ansible.builtin.file:
    mode: "0755"
    path: "{{ ansible_user_dir }}/.config/yazi"
    state: directory

- name: "Yazi | Create symlink to role files directory"
  ansible.builtin.file:
    src: "{{ role_path }}/files"
    dest: "{{ ansible_user_dir }}/.config/yazi"
    state: link
    force: true
