---
- name: Install the dunst package
  become: true
  community.general.pacman:
    name: dunst
    state: present

- name: Ensure the dunst configuration directories exists
  ansible.builtin.file:
    path: "{{ dunst_config_dir }}"
    state: directory
    mode: '0755'

- name: Copy the dunst configuration file
  ansible.builtin.copy:
    src: files/dunstrc
    dest: "{{ dunst_config_file }}"
    mode: '0644'
