#SPDX-License-Identifier: MIT-0
---
# defaults file for roles/fonts
fonts_dir: $HOME/.local/share/fonts
nerd_fonts_version: 3.4.0
nerd_fonts_repo: "https://github.com/ryanoasis/nerd-fonts/releases/download/v{{ nerd_fonts_version }}"

fonts: {
  "3270": "{{ nerd_fonts_repo }}/3270.zip",
  "BigBlueTerm": "{{ nerd_fonts_repo }}/BigBlueTerminal.zip",
  "FiraMono": "{{ nerd_fonts_repo }}/FiraMono.zip",
  "IBMPlexMono": "{{ nerd_fonts_repo }}/IBMPlexMono.zip",
}
