---
build_packages:
  - build-essential
  - libpam0g-dev
  - libxcb-xkb-dev
  - xauth
  - xserver-xorg
  - brightnessctl

ly_repo_url: "https://codeberg.org/fairyglade/ly.git"
ly_repo_path: "/opt/ly"

zig_version: 0.15.2
zig_archive_url: "https://ziglang.org/download/{{ zig_version }}/zig-x86_64-linux-{{ zig_version }}.tar.xz"
zig_path: "/opt/zig"
