#SPDX-License-Identifier: MIT-0
---
# tasks file for roles/common
- name: Install needed programs
  ansible.builtin.package:
    name:
      - polkitd
      - openssh-client
      - btop
      - man-db
      - which
      - fd-find
      - lsd
    state: present
  become: true
