#SPDX-License-Identifier: MIT-0
---
# tasks file for roles/common
- name: Install needed programs
  ansible.builtin.package:
    name:
      - polkit
      - openssh
      - btop
    state: present
  become: true
