---
- name: Install the slstatus build requirements
  become: true
  community.general.pacman:
    name: "{{ slstatus_build_requirements }}"
    state: present

- name: Ensure the slstatus directory exists
  ansible.builtin.file:
    path: "{{ slstatus_workspace_dir }}"
    state: directory
    mode: '0755'

- name: Clone the custom slstatus repo # noqa: latest[git]
  ansible.builtin.git:
    repo: "{{ slstatus_ssl_repo }}"
    dest: "{{ slstatus_workspace_dir }}"
  notify: Slstatus_make
