---
# tasks file for roles/dnfRepo
- name: Check if EPEL repo is already configured.
  stat:
    path: "{{ epel_repofile_path }}"
  register: epel_repofile_result

- name: Import EPEL GPG key.
  rpm_key:
    key: "{{ epel_repo_gpg_key_url }}"
    state: present
  register: result
  until: result is succeeded
  retries: 5
  delay: 10
  when: not epel_repofile_result.stat.exists
  ignore_errors: "{{ ansible_check_mode }}"
  become: true

- name: Enable CodeReady Builder
  ansible.builtin.ini_file:
    path: /etc/yum.repos.d/rocky.repo
    section: "crb"                     
    option: "enabled"
    value: "1"                        
    mode: '0644'                     
  when: ansible_distribution == "Rocky"
  become: true

- name: Install EPEL release from official source
  ansible.builtin.dnf:
    name: "{{ epel_repo_url }}"
    state: present
  become: true
