---
- name: Install ly display manager with pacman
  become: true
  community.general.pacman:
    name: ly
    state: present

- name: Copy the ly configuration
  become: true
  ansible.builtin.copy:
    src: files/config.ini
    dest: "{{ ly_config_file }}"

- name: Enable the ly systemd service
  become: true
  ansible.builtin.systemd_service:
    name: ly@tty2
    enabled: true

- name: Disable the getty systemd service
  become: true
  ansible.builtin.systemd_service:
    name: getty@tty2
    enabled: false
