---
os_packages:
  - brightnessctl
  - dmenu
  - feh
  - flameshot
  - gimp
  - imagemagick
  - kitty
  - libx11
  - libxft
  - libxinerama
  - mate-polkit
  - picom
  - polkit
  - wireplumber
  - xorg
  - xorg-xinit
