---
os_packages:
  - brightnessctl
  - feh
  - flameshot
  - gimp
  - imagemagick
  - kitty
  - libx11-dev
  - libxft-dev
  - libxinerama-dev
  - mate-polkit
  - picom
  - polkitd
  - wireplumber
  - xorg
