---
- name: Install archlinux build dependencies.
  become: true
  community.general.pacman:
    name: "{{ archlinux_build_requirements }}"
    state: present

- name: Install archlinux additional packages
  become: true
  community.general.pacman:
    name: "{{ archlinux_additional_packages }}"
    state: present
