---
- name: Remove existing neovim
  become: true
  ansible.builtin.package:
    name: neovim
    state: absent

- name: "Install appropriate build dependencies"
  community.general.pacman:
    name: "{{ neovim_build_requirements }}"
    state: present

- name: Ensure python-requests is installed
  ansible.builtin.pip:
    name: requests
    state: present
    virtualenv: /tmp/.venv
  become: true

- name: Compare current installed version against latest stable
  ansible.builtin.script:
    cmd: library/need_neovim_upgrade.py
    executable: /tmp/.venv/bin/python
  register: neovim_upgrade
  changed_when: neovim_upgrade.stdout | trim == 'needUpgrade'

- name: Build from source if there is a new stable version
  when: neovim_upgrade.stdout | trim == 'needUpgrade'
  block:
    - name: Clone the repo
      ansible.builtin.git:
        repo: "https://github.com/neovim/neovim"
        dest: /tmp/neovim
        single_branch: true
        version: stable

    - name: Build neovim from stable source
      become: true
      community.general.make:
        chdir: /tmp/neovim
        target: install
        params:
          CMAKE_BUILD_TYPE: RelWithDebInfo

    - name: Remove the cloned repo after build is complete
      become: true
      ansible.builtin.file:
        path: /tmp/neovim
        state: absent

- name: Ensure the neovim config and workspace dir exists
  ansible.builtin.file:
    path: "{{ neovim_dir }}"
    state: directory
    mode: '0755'
  loop:
    - "{{ neovim_config_dir }}"
    - "{{ neovim_workspace_dir }}"
  loop_control:
    loop_var: neovim_dir

- name: Clone my neovim config from github # noqa: latest[git]
  ansible.builtin.git:
    repo: "{{ neovim_ssl_repo }}"
    dest: "{{ neovim_workspace_dir }}"

- name: Link my neovim repo to the xdg config directory
  ansible.builtin.file:
    src: "{{ neovim_workspace_dir }}"
    dest: "{{ neovim_config_dir }}"
    state: link
