---
- name: "Install Batcat Application"
  ansible.builtin.package:
    name: bat
    state: latest

- name: "Batcat | Config folder"
  ansible.builtin.file:
    mode: "0755"
    path: "{{ ansible_user_dir }}/.config/bat"
    state: directory

- name: "Batcat | Create symlink to role files directory"
  ansible.builtin.file:
    src: "{{ role_path }}/files"
    dest: "{{ ansible_user_dir }}/.config/bat"
    state: link
    force: true
