---
- name: Install Dependencies
  ansible.builtin.package:
    name:
      - fontconfig
      - unzip
  become: true

- name: Simple kanji support
  become: true
  block:
    - name: Ensure locales exists
      community.general.locale_gen:
        name:
          - en_US.UTF-8
          - de_DE.UTF-8
          - ja_JP.UTF-8
        state: present

    - name: Install japanese font
      community.general.pacman:
        name: adobe-source-han-sans-jp-fonts
        state: present
      when: ansible_distribution == "Archlinux"

- name: Create fonts directory
  ansible.builtin.file:
    path: "{{ fonts_dir }}/{{ font.key }}"
    state: directory
  loop: "{{ fonts | dict2items }}"
  loop_control:
    loop_var: font

- name: Download Fonts
  ansible.builtin.unarchive:
    src: "{{ font.value }}"
    dest: "{{ fonts_dir }}/{{ font.key }}"
    remote_src: true
  loop: "{{ fonts | dict2items }}"
  loop_control:
    loop_var: font
  register: download_fonts

- name: Run fc-cache command
  ansible.builtin.command: fc-cache
  when: download_fonts.changed
